line-length = 120
exclude = [
  ".git",
  ".venv",
  "__pycacne__",
]

[lint]
select = ["E","F","I"]
ignore = [
  "E501",
  "E203",
  "E251",
]

[lint.isort]
section-order = ["future","standard-library","third-party","first-party","local-folder"]
split-on-trailing-comma=true

[format]
quote-style='double'
indent-style='space'
line-ending='auto'
